# Generated by Django 2.1.4 on 2018-12-26 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_auto_20181226_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitner_model',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
