# Generated by Django 2.1.4 on 2018-12-26 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_messagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='messagelog',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='leitner_model',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='source.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagelog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='source.User'),
            preserve_default=False,
        ),
    ]
