# Generated by Django 2.1.4 on 2018-12-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0006_user_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(unique=True)),
                ('telegram_welcome_text', models.CharField(max_length=400)),
                ('telegram_start_text', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
