# Generated by Django 2.1.4 on 2018-12-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0008_auto_20181227_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='enter_answer_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='setting',
            name='telegram_start_text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='setting',
            name='telegram_welcome_text',
            field=models.TextField(max_length=4000),
        ),
    ]
