# Generated by Django 2.1.4 on 2018-12-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0009_auto_20181227_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='metadata',
            field=models.CharField(default='', max_length=90000),
            preserve_default=False,
        ),
    ]
