# Generated by Django 2.1.4 on 2018-12-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0011_auto_20181227_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='queue',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
