# Generated by Django 2.1.4 on 2018-12-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0012_user_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='levels',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
