# Generated by Django 2.1.4 on 2018-12-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0013_user_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_to_ask',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
