# Generated by Django 2.1.4 on 2018-12-27 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0014_user_time_to_ask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_to_ask',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 7, 0)),
        ),
    ]
