# Generated by Django 2.1.4 on 2018-12-28 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0015_auto_20181227_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitner_model',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.User'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.User'),
        ),
    ]
